set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR STM8)

if(DEFINED ENV{STM8_TOOLCHAIN_DIR})
  set(BINUTILS_PATH $ENV{STM8_TOOLCHAIN_DIR})
  set(TOOLCHAIN_PREFIX $ENV{STM8_TOOLCHAIN_DIR}/bin/)
else()
  if (WIN32)
  message(FATAL_ERROR "ARM_TOOLCHAIN_DIR Not Defined")
  endif()
endif()

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

if (WIN32)
set(CMAKE_C_COMPILER "${TOOLCHAIN_PREFIX}sdcc.exe" CACHE FILEPATH "C Compiler path")
set(CMAKE_ASM_COMPILER "${TOOLCHAIN_PREFIX}sdcc.exe")
set(CMAKE_CXX_COMPILER "${TOOLCHAIN_PREFIX}sdcc.exe" CACHE FILEPATH "C++ Compiler path")
else()
set(CMAKE_C_COMPILER "${TOOLCHAIN_PREFIX}sdcc" CACHE FILEPATH "C Compiler path")
set(CMAKE_ASM_COMPILER "${TOOLCHAIN_PREFIX}sdcc")
set(CMAKE_CXX_COMPILER "${TOOLCHAIN_PREFIX}sdcc" CACHE FILEPATH "C++ Compiler path")
endif()

set(CMAKE_OBJCOPY ${TOOLCHAIN_PREFIX}objcopy CACHE INTERNAL "objcopy tool")
set(CMAKE_SIZE_UTIL ${TOOLCHAIN_PREFIX}size CACHE INTERNAL "size tool")

set(CMAKE_C_STANDARD    11)
set(CMAKE_CXX_STANDARD  11)

# Disable compiler checks.
set(CMAKE_C_COMPILER_FORCED TRUE)
set(CMAKE_CXX_COMPILER_FORCED TRUE)

set(CMAKE_FIND_ROOT_PATH ${BINUTILS_PATH})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)